
const UtilityActionTypes = {
    TOGGLE_ON_UTILITY_FORM:'TOGGLE_ON_UTILITY_FORM',
    TOGGLE_OFF_UTILITY_FORM:'TOGGLE_OFF_UTILITY_FORM',
    FETCH_UTILITIES:'FETCH_UTILITIES',
    DELETE_UTILITY:'DELETE_UTILITY',
    UPDATE_UTILITIES:'UPDATE_UTILITIES'
};

export default UtilityActionTypes;