const ExpensesActionTypes = {
    TOGGLE_ON_EXPENSE_CATEGORY_FORM:'TOGGLE_ON_EXPENSE_CATEGORY_FORM',
    TOGGLE_OFF_EXPENSE_CATEGORY_FORM:'TOGGLE_OFF_EXPENSE_CATEGORY_FORM',
    FETCH_EXPENSES_CATEGORY:'FETCH_EXPENSES_CATEGORY',
    FETCH_TRANSACTIONS:'FETCH_TRANSACTIONS',
    TOGGLE_ON_TRANSACTION_FORM:'TOGGLE_ON_TRANSACTION_FORM',
    TOGGLE_OFF_TRANSACTION_FORM:'TOGGLE_OFF_TRANSACTION_FORM',
    EXPENSE_CATEGORY_SELECTED_NAME:'EXPENSE_CATEGORY_SELECTED_NAME'
};

export default ExpensesActionTypes;