const SelectedPagesActionTypes = {
    UTILITIES_SELECTED:'UTILITIES_SELECTED',
    DEBTS_SELECTED:'DEBTS_SELECTED',
    EXPENSES_SELECTED:'EXPENSES_SELECTED',
    MAIN_MENU_SELECTED:'MAIN_MENU_SELECTED'
};

export default SelectedPagesActionTypes